[package]
name = "kettle"
version = "0.1.0"
edition = "2021"
license = "GPLv3-only"

[dependencies]
bootloader = "0.10.11"
font8x8 = { version = "0.3.1", features = ["unicode"], default-features = false }
